server:
  port: 8100

gateway:
  api:
    v1: '/v1'

camel:
  springboot:
    # The Camel context name
    name: Gateway

# Binding health checks to a different port
management:
  port: 8101

# disable all management enpoints except health
endpoints:
  enabled: false
  health:
    enabled: true

# The application configuration properties
quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s