version: '3.1'

services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.5
    restart: always
    volumes:
      - zookeeper-data:/data
      - zookeeper-datalog:/datalog
      - zookeeper-logs:/logs
    environment:
      zk_id: "1"
    network_mode: "host"

  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.12-2.2.1
    restart: always
    volumes:
      - kafka-data:/kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: "127.0.0.1:2181"
    network_mode: "host"


volumes:
  zookeeper-data:
  zookeeper-datalog:
  zookeeper-logs:
  kafka-data: